trussed-dev/littlefs2

src/fs.rs
src/io.rs

Instead of panicking if an operation in a callback fails, convert the Rust enum to an error code and return it to littlefs2.

Propagate errors in callbacks

---

src/driver.rs
src/fs.rs
src/macros.rs

The definition with an immutable self clashes with the [`ReadStorage`](https://docs.rs/embedded-storage/latest/embedded_storage/trait.ReadStorage.html) trait from the embedded_storage crate which has read(&mut self, ...). Allowing the object to be mutated is more generic, so change our Storage trait accordingly.

driver::Storage::read(&self -> &mut self)

---

CHANGELOG.md
src/fs.rs
src/lib.rs
src/path.rs
tests/test_serde.rs

Previously, we could simply construct a PathBuf from a str using PathBuf::from, but not a Path.  This patch changes this by adding the Path::from_str_with_nul method and the path! macro.  This even makes it possible to create Path constants.

Support constructing const Path from str

---

src/consts.rs
src/driver.rs
src/fs.rs
src/io.rs
src/io/prelude.rs
src/lib.rs
src/path.rs
src/tests.rs
tests/test_serde.rs

Fixes https://github.com/trussed-dev/littlefs2/issues/35

Correct remove_dir_all_where recursion handling / Fix #35

---

src/fs.rs

This PR adds a check in the remove_dir_all method to avoid removing the root directory. This Gives a simple fix to the case where one wants to remove all files in the filesystem, and therefore calls remove_dir_all on `/`, which would previously fail because it can't delete the root.
Fix #45

Fix deletion of root directory

---

CHANGELOG.md
src/lib.rs
src/object_safe.rs

The Storage trait is not object safe, and the File and Filesystem struct have the Storage implementation as a type parameter.  This can make it hard to write code that works with multiple storage implementations, and it can also lead to increased binary size as the filesystem operations are monomorphized for all storage implementations.
This patch introduces three new traits, DynFile, DynFilesystem and DynStorage, that are object-safe wrappers for the File, Filesystem and Storage types.  Some functionality cannot be expressed directly in these traits and is moved into helper functions instead, e. g. callbacks with arbitrary return types or methods using const generics.
----
Let me know if you have better ideas for the module name …

Add object-safe traits for File, Filesystem, Storage

---

src/path.rs

Path: Add ordering comparison functions
The ordering of path (as obtained when iterating over a directory) in Littlefs
is not exactly what is expected.
This implementation contains 2 comparision functions, one matching what is expected,
and one matching the iteration order of littlefs directories,
as described in https://github.com/littlefs-project/littlefs/issues/923
The fact that directories are ordered is documented:
https://github.com/littlefs-project/littlefs/blob/f53a0cc961a8acac85f868b431d2f3e58e447ba3/SPEC.md?plain=1#L304

 Path: Add ordering comparison functions 

---

src/fs.rs

These commits fix multiple instances of undefined behavior as originally discussed via email with @sosthene-nitrokey.
The struct `Allocation` is initialized so that its config retains multiple references to the cache. 
```
alloc.config.buffer = & mut alloc.cache *mut _ as *mut cty::c_void;
```
When this reference or any other reference to one of the caches within `alloc` is mutated in C, it will invalidate all other mutable references to `alloc`. Wrapping each cache in an `UnsafeCell` prevents this from occurring, since foreign writes do not affect the validity of a permission to a location if that location is covered by an `UnsafeCell`. 
The structure of the C API uses multiple linked lists to contain objects of type `lfs_file` and `lfs_dir`. For example:
```
pub struct lfs_file {
pub …
```

Fixes undefined behavior due to improper use of `&mut`

---

CHANGELOG.md
src/fs.rs

When mounting a filesystem, often code like this is used:
```
if !Filesystem::is_mountable(alloc, storage) {
Filesystem::format(storage).ok();
}
Filesystem::mount(alloc, storage)
```
This mounts the filesystem twice because Filesystem::is_mountable is equivalent to Filesystem::mount(...).is_ok().  Depending on the storage implementation, mounting the filesystem can have significant cost. But directly calling Filesystem::mount and re-mounting in the error case is prohibited by the borrow checker.
This patch adds a mount_or_else method that accepts a callable that is called on mount error.  Afterwards, mounting is re-tried.

Add Filesystem::mount_or_else

---

CHANGELOG.md
src/lib.rs

By using a temporary const value, we can enforce that the path! macro always causes a compiler error for illegal values even if it is not used in a const context.  This makes it easier to write correct code.

Enforce const evaluation in path! macro

---

CHANGELOG.md
src/fs.rs
src/lib.rs
src/path.rs
src/tests.rs

This patch changes all constructors and conversion traits for `Path` and `PathBuf` to be fallible (except for `From<&Path> for PathBuf`).  It also adds explicit invariants to the path types and marks its functions as const where possible.
Fixes: https://github.com/trussed-dev/littlefs2/issues/63

Remove panicking path conversions

---

.github/workflows/ci.yml

This job no longer works so this patch removes it from the GitHub Actions workflow.  Users should refer to docs.rs instead.

Remove deploy docs job

---

CHANGELOG.md
src/fs.rs
src/io.rs
src/object_safe.rs
src/tests.rs

This PR splits the `Error` enum into an `Error` struct and a non-exhaustive `ErrorKind` enum.  This makes it possible to add support for new error codes without breaking compatibility.  The PR also removes the edge case of `Error` instances for non-negative return values indicating success.
See this issue for context and discussion:
- https://github.com/trussed-dev/littlefs2/issues/55
Contrary to the suggestion in https://github.com/trussed-dev/littlefs2/issues/55#issuecomment-2024943423, this implementation does not provide a `fn error(&self) -> Option<ErrorKind>` on `Error`.  It would again cause the problem that users could rely on this method returning `None` for some currently unsupported error.  Instead, `Error` implements `PartialEq<ErrorKind>` so that users can compare it directly …

Refactor error types

---

.github/workflows/ci.yml
src/driver.rs
src/tests.rs

This patch adds clippy and rustfmt to the CI and fails the workflow if cargo doc shows a warning.

Extend CI checks

---

.github/workflows/ci.yml
CHANGELOG.md
Cargo.toml
README.md
core/CHANGELOG.md
core/Cargo.toml
core/src/consts.rs
core/src/fs.rs
core/src/io.rs
core/src/lib.rs
core/src/object_safe.rs
core/src/path.rs
src/consts.rs
src/fs.rs
src/io/prelude.rs
src/lib.rs
src/object_safe.rs
src/tests.rs

This PR introduces a `littlefs2-core` crate that provides an interface that does not depend on a specific littlefs2 version.  The goal is to make applications using `littlefs2` easier to maintain as they no longer need to be updated if a `littlefs2` implementation detail is changed.
The API of `littlefs2` is mostly unaffected by this change as all moved items are re-exported under their old name.  Some changes are required to de-couple the moved types from the actual implementation.  See the changelog for details.
Contrary to the initial proposal in https://github.com/trussed-dev/littlefs2/issues/55, this does not move the `DynStorage` trait.  From my point of view, it is coupled too tightly to the actual storage implementation that could be subject to change.  Also, there is no real …

Introduce littlefs2-core crate

---

core/src/fs.rs
core/src/io.rs

This patch applies those changes from https://github.com/trussed-dev/littlefs2/pull/69 that affect the core crate.

core: Use c_int where applicable

---

CHANGELOG.md
core/src/fs.rs
core/src/object_safe.rs
src/fs.rs
src/object_safe.rs
src/tests.rs

This patch refactory the API to read and write attributes so that the buffer is always provided by the caller.  This means that the caller is not required to always use a 1 kB buffer even if the attribute length is much smaller.
Fixes: https://github.com/trussed-dev/littlefs2/issues/75

Refactor attributes API

---

.github/workflows/ci.yml
CHANGELOG.md
Cargo.toml
core/Cargo.toml
core/src/fs.rs
core/src/object_safe.rs
src/fs.rs
src/object_safe.rs
src/tests.rs

The dir-entry-path feature has been enabled by default and only adds a very small overhead.  To decrease complexity, this patch removes the feature and always enables the previously feature-gated code.
Fixes: https://github.com/trussed-dev/littlefs2/issues/76

 Remove dir-entry-path feature

---

.github/workflows/ci.yml
CHANGELOG.md
core/Cargo.toml
core/src/lib.rs
core/src/object_safe.rs

The `DynFile::read_to_end`, `DynFilesystem::read` and `DynFilesystem::read_chunk` methods use a `heapless::Vec` to store a flexible amount of data.  This patch introduces a `Vec` trait that abstracts over different versions of heapless so that we can optionally support multiple heapless versions at the same time.
Fixes: https://github.com/trussed-dev/littlefs2/issues/77

core: Make heapless support optional and support multiple versions

---

core/src/io.rs

If unwrap or expect is used on a `Result<_, Error>`, the `Debug` implementation is not always optimized out.  This leads to a significant increase of the binary size. As a short-term fix, this patch changes the `Debug` implementation to always returns a static string.

core: Remove debug information from Error

---

core/src/path.rs

This improves binary size of the Nitrokey 3 firmware.

core: Never inline Path to PathBuf conversion

---

.github/workflows/ci.yml
CHANGELOG.md
src/fs.rs

This PR adds a CI job that tests compatibility with an avr target (16-bit) and fixes code that assumes that `c_int` is always `i32`.
Replaces:
- https://github.com/trussed-dev/littlefs2/pull/68
One remaining problem is that some functions cast `u32` return values to `usize`.  In most cases that should be fine because the return value is limited by the length of the input buffer and thus fits into a `usize`.  One notable exemption is `seek`.  But let’s review and fix that separately.

Handle platforms where c_int is not i32

---

examples/list.rs

This patch adds an example that reads a filesystem image from a file and prints its content.

Add list example

---

core/src/path.rs
src/fs.rs

This PR fixes warnings generated by two new clippy lints: unnecessary explicit lifetimes and empty lines after doc comments.

Fix new clippy lints

---

core/CHANGELOG.md
core/Cargo.toml
core/src/lib.rs
core/src/path.rs

This patch makes some `Path` and `PathBuf` methods const, adds new `const` helper functions and a `path_buf` macro similar to the existing `path` and releases littlefs2-core v0.1.1 with these changes.

core: Make Path and PathBuf more const-friendly and release v0.1.1

---

.github/workflows/ci.yml

`avr-none` is now a supported Tier 3 target so we no longer need the custom target definition.

ci: Use avr-none target for avr build

---

CHANGELOG.md
src/fs.rs
src/macros.rs
src/tests.rs
tests/test_serde.rs

The `const_ram_storage!` and `ram_storage!` macros used to have trait and result arguments to set the storage trait to implement and the result type to use.  As this defaulted to relative paths, it made the result of the macro dependent on the context and could cause confusion.  At the same time, there is no real use case for substituting these types.
This patch removes the arguments for good and just uses `$crate::driver::Storage` and `$crate::io::Result` instead.
----
As we prepare a breaking release, I’d like to pull in this change that fixes a very annoying macro hygiene issue.

Remove trait and result arguments from macros
